---
- hosts: localhost
  pre_tasks:
    - name: UPDATE EVERYTHING (Debian)
      become: yes
      tags: 
        - always
        - update
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

- hosts: localhost # others, media
  roles:
    - install-apt-packages
    - install-git-packages
    # - install-kali-packages
    - kali-zsh-packages

