---
- hosts: all
  pre_tasks:
    - name: UPDATE EVERYTHING (Debian)
      become: yes
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"

- hosts: all # others, media
  roles:
    - install-apt-packages
    - install-git-packages
    - change-default-shell
    - install-usr-packages
    #- copy-configs
    # - { role: install-rust, become: no }

- hosts: others, VPN, DNS
  roles:
    - ssh-config
