---
- hosts: all, localhost
  name: UPDATE
  pre_tasks:
    - name: UPDATE EVERYTHING (Debian)
      become: yes
      tags: 
        - always
        - update
        - debian-update
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: UPDATE EVERYTHING (Arch)
      become: yes
      tags: 
        - always
        - update
        - arch-update
      community.general.pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

    - name: UPDATE EVERYTHING (RPM)
      become: yes
      tags: 
        - always
        - update
        - rpm-update
      dnf:
        update_cache: true
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

- hosts: others
  name: CONFIGURE
  roles:
    - install-apt-packages
    - install-git-packages
    - change-default-shell
    - install-usr-packages
    # - { role: install-rust, become: no }
    - ssh-config

- hosts: desktops, development
  name: DESKTOP & DEV SERVER CONFIGURATION
  roles:
    #- copy-configs
