---
- hosts: proxmox
  name: BOOT NON-DEFAULT VIRTUAL MACHINES
  any_errors_fatal: true
  roles:
    - boot-vms

- hosts: proxmox
  name: START VM HOOKS
  roles:
    - vm-hooks

- hosts: all, localhost
  name: UPDATE
  pre_tasks:
    - name: UPDATE EVERYTHING (Debian)
      become: true
      tags:
        - always
        - update
        - debian-update
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: UPDATE EVERYTHING (Arch)
      become: true
      tags:
        - always
        - update
        - arch-update
      community.general.pacman:  # used to be just "pacman"
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

    - name: UPDATE EVERYTHING (RPM)
      become: true
      tags:
        - always
        - update
        - rpm-update
      ansible.builtin.dnf:
        update_cache: true
        name: "*"
        # state: "latest"
      when: ansible_os_family == "RedHat"

- hosts: others, desktops, development
  name: BASE CONFIGURE
  roles:
    - install-apt-packages
    - install-git-packages
    - change-default-shell
    - install-usr-packages

- hosts: others
  name: CONFIGURE SSH
  roles:
    - ssh-config

- hosts: proxmox_guests
  name: PROXMOX SPECIFIC
  roles:
    - enable-qemu

- hosts: desktops, development
  name: DESKTOP & DEVELOPEMENT SERVERS SETUP
  roles:
    - install-rust
    - deb-zsh-packages
    # - copy-configs
    - setup-docker
