- name: Copy .config/nvim
  tags: configs,nvim,sync
  synchronize:
    src: deb-bak/.config/nvim
    dest: ~/.config/
    owner: True
    group: True
    mode: 'push'

- name: Copy .zshrc
  tags: configs,zsh,copy
  ansible.builtin.copy:
    src: deb-bak/.zshrc
    dest: ~/.zshrc
    owner: yogurt
    group: yogurt
    mode: 'preserve'

- name: Copy zsh alias file
  tags: configs,zsh,copy
  ansible.builtin.copy:
    src: deb-bak/.zsh_aliases
    dest: ~/.zsh_aliases
    owner: yogurt
    group: yogurt
    mode: 'preserve'

- name: Copy tmux config
  tags: configs,tmux,copy
  ansible.builtin.copy:
    src: deb-bak/.tmux.conf
    dest: ~/.tmux.conf
    owner: yogurt
    group: yogurt
    mode: 'preserve'

- name: Copy powerline config
  tags: configs,zsh,copy
  ansible.builtin.copy:
    src: deb-bak/.p10k.zsh
    dest: ~/.p10k.zsh
    owner: yogurt
    group: yogurt
    mode: 'preserve'
