---

- hosts: all
   become: true
   tasks:
 
   - name: update repository index
     apt:
       update_cache: yes
 
   - name: install apt packages 
     apt:
       name: "{{ apt_packages }}"
       state: latest
